apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: f9ip7fzty-go
  janus-idp.io/tekton: f9ip7fzty-go
  backstage.io/kubernetes-id: f9ip7fzty-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: f9ip7fzty-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
